-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 23:02:29 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema awarehome
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema awarehome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `awarehome` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `awarehome` ;

-- -----------------------------------------------------
-- Table `awarehome`.`clave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awarehome`.`clave` (
  `id_clave` INT NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awarehome`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awarehome`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `clave_id_clave` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_clave_idx` (`clave_id_clave` ASC),
  CONSTRAINT `fk_usuario_clave`
    FOREIGN KEY (`clave_id_clave`)
    REFERENCES `awarehome`.`clave` (`id_clave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awarehome`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awarehome`.`sensor` (
  `id_sensor` INT NOT NULL AUTO_INCREMENT,
  `temperatura` DOUBLE NULL,
  `humedad` DOUBLE NULL,
  `gas` DOUBLE NULL,
  `fecha` DATETIME NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_sensor`),
  INDEX `fk_sensor_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_sensor_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `awarehome`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awarehome`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awarehome`.`alerta` (
  `id_alerta` INT NOT NULL AUTO_INCREMENT,
  `nombre_alerta` VARCHAR(45) NOT NULL,
  `nombre_sensor` VARCHAR(45) NOT NULL,
  `simbolo_alerta` VARCHAR(45) NOT NULL,
  `dato` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `sensor_id_sensor` INT NOT NULL,
  PRIMARY KEY (`id_alerta`),
  INDEX `fk_alerta_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_alerta_sensor1_idx` (`sensor_id_sensor` ASC),
  CONSTRAINT `fk_alerta_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `awarehome`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alerta_sensor1`
    FOREIGN KEY (`sensor_id_sensor`)
    REFERENCES `awarehome`.`sensor` (`id_sensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awarehome`.`hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awarehome`.`hogar` (
  `id_hogar` INT NOT NULL AUTO_INCREMENT,
  `descripción` VARCHAR(45) NULL,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_hogar`),
  INDEX `fk_hogar_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_hogar_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `awarehome`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
